### ISSUE TITLE
BUG: new acc steam cant connect to dotabod and not showing in dashboard

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#100]
The Steam account is not linked to dotabod. The bot can change the mmr value, but it does not show that the account is actually added to the dashboard. The same problem [CHUN](https://discord.com/channels/1039887907705593876/1063279492249944084)
![зображення](https://user-images.githubusercontent.com/91318807/212237374-4e7dc09a-ab2c-432f-b0e5-2c657bf6b7e3.png)
![зображення](https://user-images.githubusercontent.com/91318807/212236876-21bca2fa-8cfc-4e0c-ae42-bcd92a895375.png)

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/212448504-8edf264c-b593-4dc6-bb36-fccb9d8f2e6d.png)
![зображення](https://user-images.githubusercontent.com/91318807/212448393-70e1a50f-e611-4263-a3d6-6d1f19403000.png)

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/212463840-a0d05a72-3265-4464-bcef-e37627f428a4.png)

**Comment by dankYoff** [comment]
CONCLUSION: 1) The account is either not linked at all 2) The account is linked to the first linked account or is linked normally and will not be displayed on the site

**Comment by Geczy** [comment]
this turned out to be because the account is already linked to another dotabod user. we only allow one dotabod user for a steam account, so @dankYoff will ask the other person to remove it if its not used
