### ISSUE TITLE
warning if mmr seems off

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#101]
For example. If you have the rank Immortal (2120) your mmr (7000 +-500 mmr) and you can not enter more / less mmr. The same works for low mmr if you have (herald 4 ~ 1000  mmr), you can not enter yourself - 5000 mmr

Some people put this mmr incorrectly - for several reasons: either they want to show that they really have a lot of mmr, or they made a mistake and did not notice it

**Comment by Geczy** [comment]
i think they'll notice eventually and fix it later once its shown on stream and chatters point it out or something. im going to close this for now
