### ISSUE TITLE
Glypg, BB, BKB, ULTS Timing Overlay

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#110]
I know you can't follow these events, but in the future if such an opportunity arises, I'll just give you an idea how it can be combined
![зображення](https://user-images.githubusercontent.com/91318807/213056252-9febe2cd-3067-4cec-b572-1d268b9090d8.png)

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/213056690-bc7c4aac-678d-43a6-a6fc-ae89c6918130.png)

**Comment by Geczy** [comment]
nice idea :) the events aren't available but maybe there is a future possibility

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/215632242-e28953ad-981d-446a-bda8-d4bf12f601dc.png)

![зображення](https://user-images.githubusercontent.com/91318807/215632447-faef8b35-88fe-4256-a164-f36900461d5e.png)
