### ISSUE TITLE
Interactive map viewing (replay is better)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#111]
My next crazy idea.
A long time ago, I saw an interactive map of Dota 2 from [devilesk](https://github.com/devilesk/dota-interactive-map). Now it is not working, but what are its advantages:
1) You can find out at what second there will be dills on shit
2) Draw different trajectories of the figure
3) Wards showed a viewing radius and were also covered by trees
4) You could place the heroes and indicate the trajectory of their movement
5) Measure the distance and find out the time you need to complete it at a certain speed of the hero or the speed you specified

Maybe something else, but I don't remember anymore
Now its not work and the map has not been updated at all in the last 4 years(
![зображення](https://user-images.githubusercontent.com/91318807/213806091-b927ffde-79f9-4fbe-ab7c-aedd6235c9a4.png)

After that, I came across the [parsing of the match](https://github.com/timkurvers/redota/) so far in the browser (you can watch any saved or id match).
![зображення](https://user-images.githubusercontent.com/91318807/213807220-4d3ec2c2-0128-4e66-88d2-ee5a16805721.png)

Does it need to be implemented in the bot itself? Of course not. But I just wanted that this interesting functionality can be done in the future. For drawing I like [magma](https://magma.com)
![зображення](https://user-images.githubusercontent.com/91318807/213807594-697b3238-e662-48ce-93b0-2cdfabf1f8dd.png)

**Comment by Geczy** [comment]
where would this be shown in the stream?

**Comment by dankYoff** [comment]
It's just like a separate idea, not for dotabod. And in general. It seems to me that it simply does not combine well with twitch

**Comment by Geczy** [comment]
so its replay for the browser? its a neat crazy idea but i wont be implementing this one

ty for the ideas, keep it up 👍🏻
