### ISSUE TITLE
!roshan

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#113]
It shows what roshan 1, 2 or 3 is now, and so on, if Roshan is dead, max writes a timer after he gets up, well, things that can be obtained from him. you can also enter the status of Roshan: dead, alive, will appear at any moment. The command is not too necessary, but I think it's a cool trick, especially for viewers who just came in and wants to find out which Roshan. Write to the branch what you think, maybe what you can offer on this topic
https://discord.com/channels/1039887907705593876/1046119849014853775/1066405468710383627

**Comment by dankYoff** [comment]
found this picture just to have it
![Image](https://user-images.githubusercontent.com/91318807/215777195-4095451c-066a-4ed0-a85e-1c7e7633a8da.png)

**Comment by Geczy** [comment]
we now have it, just no toggle in dashboard for it to turn it off yet
