### ISSUE TITLE
!voting

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#116]
Add a voting command that will send a message:
1) The vote was taken for this game: "Will we win the game on Pugna?". Blues voted "Yes" - 75% (150,000) | Pink voted "No" - 25 (50,000)
2) Voting is disabled on this channel
3) Voting is not available for this channel

**Comment by Geczy** [comment]
i don't see a big use for this, i'm going to close it 

you can view the current bet that is taking place already in twitch chat by clicking channel points 👌
