### ISSUE TITLE
translation information

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#117]
Add to the server, a separate channel/table, which will show who translates the bot in different languages and the percentage of the translated text. This will be useful for those people who are engaged in translation, they will always know whether an update has been released and the text needs to be translated.
![зображення](https://user-images.githubusercontent.com/91318807/213924107-abf1f18a-d419-4e06-bded-06d193592b1f.png)

**Comment by dankYoff** [comment]
When new changes in the translation are released, the bot tags a separate role and people understand that a new text has been released, which then needs to be translated

**Comment by dankYoff** [comment]
Add a pop-up text/full translation of a phrase, so that the quality of the translation itself increases and there are no errors in Slavic languages with declension

**Comment by dankYoff** [comment]
since there is already crowdin on it, you can normally see the percentage of translation of any language

![Image](https://user-images.githubusercontent.com/91318807/215470831-30995529-fd54-4af8-86a0-d82678bc47ff.png)



![Image](https://user-images.githubusercontent.com/91318807/215471854-c4687d18-99fc-4bc4-b1f7-218d83e05d37.png)

**Comment by Geczy** [comment]
if new untranslated phrases appear crowdin can notify you 

but also i just setup discord bot, so it will ping us whenever there's a new english translation string added or updated

https://discord.com/channels/1039887907705593876/1058426237338517574/1069614208003604520
