### ISSUE TITLE
show the minimap and roshan (aegis) in Live preview

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#120]
![зображення](https://user-images.githubusercontent.com/91318807/214552016-915e535e-9e96-44ae-917f-f9aa8cd18e9b.png)

**Comment by dankYoff** [comment]
and depending on the user's settings, disable or enable them

**Comment by Geczy** [comment]
they show if you kill rosh or pick up aegis in a game. no?

**Comment by dankYoff** [comment]
Yes, they show, I mean like with the !vl command - if you turned it off, then no, it is not displayed in Live preview (not in OBS). The same can be done for the minimap and for roshan (aegis) (although I don't know if it is necessary to do it at all, it's just an idea)

**Comment by Geczy** [comment]
if it's turned off, the live preview won't show roshan or aegis

i don't understand

**Comment by Geczy** [comment]
do you mean show all even if the roshan is not dead in a live bot match ? 

the live preview just waits for you to get into a game, you can join a live bot match, and kill roshan to see 
it will show minimap blocker too etc

**Comment by dankYoff** [comment]
I understood... it was my mistake, because I thought that it was possible to display the settings, and this is exactly the online reproduction of what the streamer sees
