### ISSUE TITLE
make a pick blocker bigger + mute dota (on pick stage or a pick hero)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#121]
For stream snipers, it is very easy to recognize which hero has been picked. Also come up with a way to confuse the dota, since the hero can say a phrase and it will be clear what kind of hero it is. Or then the streamer himself must understand this and exclude the hero voices

### WR
![зображення](https://user-images.githubusercontent.com/91318807/214554806-1d04d46e-fd90-4c44-915c-88a1fdb5eaf7.png)
### Ogre mage
![зображення](https://user-images.githubusercontent.com/91318807/214555526-d26347fe-d49f-41a2-b9e8-ad22c215a83b.png)

**Comment by Geczy** [comment]
its kind of impossible unless i also block the enemy or ally player names, do you think i should do that? because the blocker will have to reach all the way up

**Comment by Geczy** [comment]
see even right side for pugna will be showing, maybe hbave to block this angle too 

![image](https://user-images.githubusercontent.com/1036968/214589573-5f73ee45-f6d7-4666-9c62-7ea3c58cd97d.png)


![image](https://user-images.githubusercontent.com/1036968/214589658-697a5089-92f0-4d2a-a079-f7b2b4aa0edf.png)

**Comment by dankYoff** [comment]
I think it is better to close it completely, because if a person includes this function, he expects that his hero will not be seen, and the fact that it will cover the names of others, I think it is not a problem.

**Comment by Geczy** [comment]
so just block all this, but not the top bar hero & rank, got it

![image](https://user-images.githubusercontent.com/1036968/214592994-24b3539e-3c40-4c6c-9ec8-434bdf100469.png)

**Comment by Geczy** [comment]
and this blocker is only shown for a couple seconds while the enemy is still picking the same pick phase, so i think its ok to block player names, and block more things like inventory, you're right. when next blocker is shown it will be revealed very soon anyway

**Comment by dankYoff** [comment]
yeah, and block for right

> see even right side for pugna will be showing, maybe hbave to block this angle too
> ![image](https://user-images.githubusercontent.com/1036968/214589573-5f73ee45-f6d7-4666-9c62-7ea3c58cd97d.png)

**Comment by Geczy** [comment]
what about this area where it shows clock & strategy time. do heroes ever bleed into this? 

![image](https://user-images.githubusercontent.com/1036968/214593653-a083e9b7-8dbe-4732-b545-1bb17a353994.png)

**Comment by dankYoff** [comment]
> як щодо цієї області, де він показує годинник і час стратегії. герої колись стікають кров'ю в це?
> 
> ![image](https://user-images.githubusercontent.com/1036968/214593653-a083e9b7-8dbe-4732-b545-1bb17a353994.png)

haven't seen it before, maybe it's better to ask it in discord

**Comment by dankYoff** [comment]
And 1 more, can you mute the dota when choosing a hero? Because the hero during the peak can say a phrase or dota play the sound of that hero's ult

**Comment by Geczy** [comment]
no, i can only change scenes, and only if they are using OBS 

so the streamer could setup a new scene that has dota game client muted, and then i can switch to that

https://github.com/obsproject/obs-browser#js-bindings

**Comment by Geczy** [comment]
skywrath can get in the way of strategy time & clock 😢 

![image](https://user-images.githubusercontent.com/1036968/214600323-81319241-afab-4494-98a2-8e8ce1d8049b.png)

**Comment by Geczy** [comment]
ill just make left blocker bigger, i think if you see tiny wing near clock it's not a big deal, so will leave that. the issue was above the hero anyway

![image](https://user-images.githubusercontent.com/1036968/214600867-88b50c21-0c1d-4f26-99d3-12e6a202a98b.png)

**Comment by Geczy** [comment]
ok made this change, we will see how it looks today

**Comment by dankYoff** [comment]
I want to thank you that you are quite prompt in helping and responding to others. That's why I decided to think about dotabod ideas. I used to think that someone should create a top twitch bot for dota and now I realize that I can somehow influence this process (it's like my mini dream).

But I'm just always suggesting ideas, and you have to decide for yourself whether to do it or not.
