### ISSUE TITLE
courier overlay

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#124]
Show items and time in the form of a bar for which the courier will pass
![зображення](https://user-images.githubusercontent.com/91318807/215057905-07a22710-13c5-4c54-9e95-68a10e499713.png)

**Comment by Geczy** [comment]
get items on courrier with !courrier to know what items are on it

that way if its on the way, or if courrier died, chat can find out whats missing

**Comment by Geczy** [comment]
issues: 

1. streamer could buy item directly onto courier, it will never reach stash, so we won't know what item it is. too many items cost the same amount of gold. like 900 gold = 3 recipes, morbid mask, gem
2. courier death events dont exist

sadly this can't be an accurate feature so setting as wont do for now :(

**Comment by dankYoff** [comment]
![Image](https://user-images.githubusercontent.com/91318807/215633905-bf16eaf2-16b9-48ac-84f8-f21f6ee1ff10.png)
