### ISSUE TITLE
Delete past kill streak

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#126]
Is it possible to make the bot able to delete the past message on a thread so it doesn't spam the chat![зображення](https://user-images.githubusercontent.com/91318807/215061783-d542a1e2-5630-4a5d-8a1b-298f5ee58646.png)

**Comment by Geczy** [comment]
it is possible, but people will then see "message deleted" right?

**Comment by dankYoff** [comment]
I don't know how it works, but you can test it

**Comment by dankYoff** [comment]
or for example increase the time for the kill streak (but I don't like it)

**Comment by Geczy** [comment]
<message deleted> will show because it was already in chat, so it will still be a lot of spam. need a better solution

can wait longer than 15s but then killstreak is too long

maybe end of match killstreak stat?

**Comment by dankYoff** [comment]
yeah its better

**Comment by dankYoff** [comment]
I thought and it's better to leave it as it is. Because if you have an active chat, it will look normal in the chat itself and will not seem like spam
