### ISSUE TITLE
Account swap detector (auto refresh win-lose in obs)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#129]
When changing the account, the bot itself executes the !refresh command in order to update the win/loss statistics in the OBS overlay

**Comment by Geczy** [comment]
when changing account, the win loss remains to be the total during the entire stream as it was online

so it does not score per account, and only show WL per account, it shows all accounts

so even if i !refresh after an account swap, the WL should remain the same, unless the streamer goes offline and onlien
