### ISSUE TITLE
updates page

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#138]
![зображення](https://user-images.githubusercontent.com/91318807/215359661-1a1e0270-43f4-4b3c-99ef-18d3a85f9529.png)

![зображення](https://user-images.githubusercontent.com/91318807/215359338-0557e7cb-df12-4975-afdd-007616c4ee2d.png)

**Comment by Geczy** [comment]
will create nav link to link to changelog in dotabod discord

**Comment by dankYoff** [comment]
discord://discord.com/channels/1039887907705593876/1069124160179163146

**Comment by dankYoff** [comment]
Frequency depends on the number/volume of updates. I think 10 normal updates are enough to create a post or you can wait and create a big post. I think it already depends on your feeling, whether there is enough information for the patch or not
