### ISSUE TITLE
!smurf | СhatGPT

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#139]
#174
The solution I see, and it will be relevant, is to integrate with ChatGPT myself, where it will respond to this command. People will know that this is the machine that counts and will not think that the bot is accusing someone or telling the truth. I think it will be interesting.

ChatGPT I think Nature Prophet is a smurf. The chance of this is 87%. Hm....

Also you can name it !aismurf, !smufAI or just !smurf
![зображення](https://user-images.githubusercontent.com/91318807/216614145-d78c36e9-5b04-41af-b305-ac11aed62505.png)

**Comment by dankYoff** [comment]
https://www.dota2protracker.com/player/Miracle%20(smurf%202)#

**Comment by dankYoff** [comment]
// Algorithm:

//1. Calculate GPP, KDA, and damage by averaging the performance parameters over multiple games.

//2. Compare the calculated averages against the average performance of other players in the same game.

//3. Compute the standard deviation between the player’s calculated averages and the average performance of other players in the same game.

//4. If the standard deviation is greater than a certain threshold, then it is likely that the player is a smurf/booster.

//5. Output the probability of the player being a smurf/booster.

**Comment by Geczy** [comment]
i wont integrate with chatgpt, too many complications right now with their api (its not public) 

so it requires a roundabout way to integrate and its not officially supported
