### ISSUE TITLE
hide mmr option for multiple accounts

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#16]
you can fully hide mmr but you can't hide mmr for certain accounts

this should hide the badge ingame when playing that account

or give an option to show the main badge ingame?

**Comment by Woody3797** [comment]
i think to make it less confusing for viewers, just show the MMR/medal of the current account streamer is using.
if streamer has current account hidden, then no MMR or badge shown

**Comment by Geczy** [comment]
a streamer wanted main badge shown when playing on a smurf. so will likely just offer both as an option

**Comment by Geczy** [comment]
only the badge for the account playing is shown now. so this issue is invalid 

streamer can set mmr to 0 so it doesn't show
