### ISSUE TITLE
!lg add the hero the streamer played on

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#167]
even if no one caught up with you from the last game
![Image](https://user-images.githubusercontent.com/91318807/216210224-2ede4d88-9a12-4938-b822-fe917fb29356.png)

![Image](https://user-images.githubusercontent.com/91318807/216212383-0ae34f8b-b5a5-4939-bf56-4c2f2b3d261d.png)

**Comment by Geczy** [comment]
@gorgc played anti-mage. here's last game: dotabod.com

**Comment by dankYoff** [comment]
Not playing with anyone from. Last game on Night Stalker. Here's last game: [dotabuff.com/matches/6998694233](https://dotabuff.com/matches/6998694233)
