### ISSUE TITLE
remove aegis timer when we can

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#17]
only two conditions allow us to hide aegis timer:

* when streamer dies and has aegis
* when streamer kills the player that has aegis

maybe a third condition, when the team without aegis scores 5 points (that means its a teamwipe) within like 1 minute. but this one is a little sus, not sure if its always true.

cause enemy can die to a neutral camp or get denied otherwise, and then team wont score so itll still be 4

**Comment by XenSide** [comment]
You could use global GSI information (even tho 90s delayed) as very often the aegis is lost a lot before 210s (5 min - 90s delay) and that would still give more up-to-date information than just leaving it up untill expiry time.
