### ISSUE TITLE
delete aegis overlay instantly if hero die

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#170]
instantly (no need to wait 5 minutes for the timer to expire)
you can track the time of the hero's revival (for example, if the ursa died for 40 seconds?)

if we know that Ursa has an aegis and we know the event of death: the time of rebirth, the very fact of death. Then we can set a countdown of 5 seconds and delete the aegis after that time

**Comment by Geczy** [comment]
already removing aegis overlay if streamer dies
