### ISSUE TITLE
add plural for commands that need it

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#172]
in the crowdin, for some teams there is no plural

**Comment by Geczy** [comment]
do you know which strings those are? https://github.com/dotabod/backend/blob/master/web/locales/en/translation.json

**Comment by dankYoff** [comment]
+{{bountyValue}} gold from bounty ({{totalBounties}}/4) EZ Clap Thanks {{heroNames}} SeemsGood
{{minutes}}m long
Rosh deaths: {{num}} · Next drop: cheese, agh's blessing, and refresher shard.
