### ISSUE TITLE
notp chatter (need add 30 to timeNoTP)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#173]
### I did some research and came to the conclusion:
1) that the bot is working correctly :)
2) streamers are not happy when a bot laughs at them xD
3) you can make this feature always on 😆, but it is better not to do that

EXAMPLES (WASTE OF TIME, JUST ADD +30 SEC)

### FIRST (https://www.twitch.tv/videos/1726495125?t=0h39m25s)

Steps
1. 28:24, doing tp on base (no tp)
2. 28:56 (32 sec dotabod write @henry where's your tp HECANT [beta feature]). Henry did not like this chatter command, and off it
3. 41:54-39:58 = 1:56 = 116 sec 
![Image](https://user-images.githubusercontent.com/91318807/216504136-0b83661c-386e-4642-bc4e-3ba6056437c7.png)

ALL RIGHT 👍 

### SECOND (https://www.twitch.tv/videos/1726495125?t=2h1m19s)

Steps
1. 31:17, doing tp (no tp)
2. 31:50 (33 sec dotabod write @henry where's your tp HECANT [beta feature]). Henry did not like this chatter command, and off it
3. 42:52-43:16 = 24 sec

![Image](https://user-images.githubusercontent.com/91318807/216505926-9b3571f1-0de7-4b80-9ada-c241802041d5.png)

ALL RIGHT 👍

**Comment by Geczy** [comment]
added +30
