### ISSUE TITLE
wl overlay does not update immediately after the end of the game

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#177]
* need +- 3 min to update it
* I noticed that some streamers sometimes take a long time to load the result of the game. Maybe set a 1.5-second delay for the appearance of the overlay after the end of the game (in the main menu)

https://www.twitch.tv/videos/1724869032?t=0h58m56s
https://www.twitch.tv/videos/1724869032?t=1h01m43s

**Comment by Geczy** [comment]
its fixed
