### ISSUE TITLE
!coolness | Random number

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#179]
For example, artificial intelligence analyzes the streamer's nickname/avatur and gives the following result. You can also just make a random number, but it's not interesting

A fan command that shows the amount of self-confidence (in CIS "чсв", SO POPULAR CAPS LOCK MODE)

example
ЧСВ: 129%. It seems that there is nothing cooler in the world than you.

**Comment by Geczy** [comment]
leaving this to streamelements, trying to add dota only features rn
