### ISSUE TITLE
respond to disabled command

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#185]
can you make the bot reply with Jebaited
if someone does !mmr in a channel where mmr tracker is disabled gorgcHmm

idea from MorTal. @streamer disabled this command, type !commads to see the full list of working commands
or a public page with commands #131

**Comment by dankYoff** [comment]
idea from MorTal. @streamer disabled this command, type !commads to see the full list of working commands

**Comment by Geczy** [comment]
i finished this
