### ISSUE TITLE
add delay to dotabod game events

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#19]
basically delay anything except commands

* twitch predictions
* chatters

allow this to be configurable

need a global `say(channel, msg, nDelay)` probably

```
GSI Delay (in seconds)

Specify the amount of seconds to delay the GSI data by. This delay should match your stream delay. (max 300s)
```

**Comment by Geczy** [comment]
we can get the delay for channels automatically using:

https://dev.twitch.tv/docs/api/reference#get-channel-information

**Comment by dankYoff** [comment]
!delay
![зображення](https://user-images.githubusercontent.com/91318807/215260601-78b30e09-f361-4714-9551-d03581b6f9a7.png)

https://discord.com/channels/1039887907705593876/1068557662536597595/1068557662536597595

**Comment by Geczy** [comment]
done
