### ISSUE TITLE
mmr synchronization (!mmr and dashboard)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#192]
![Image](https://user-images.githubusercontent.com/91318807/216980721-2f978270-7196-46b8-a55e-df2fe0ab4dab.png)

**Comment by Geczy** [comment]
can you verify that there is a bug here? is it everyone or just bakabot ?

**Comment by dankYoff** [comment]
for me, the mmr in the dashboard is also not updated

**Comment by Geczy** [comment]
seems fixed
