### ISSUE TITLE
chat not responding after banning dotabod

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#193]
https://discord.com/channels/1039887907705593876/1068516739576496218

![Image](https://user-images.githubusercontent.com/91318807/216981546-62241cac-272e-4106-ab60-c6aa7ca15102.png)

**Comment by Geczy** [comment]
https://discord.com/channels/325552783787032576/350012219003764748/1072161556739137596

left some details here about it to twurple devs

**Comment by dankYoff** [comment]
Are you genius or what?
