### ISSUE TITLE
olive (not hero name)

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#204]
https://www.twitch.tv/videos/1732051552?t=01h57m23s
![Image](https://user-images.githubusercontent.com/91318807/217628930-9ff5ccbd-1284-45b2-a4cf-e9ef779ad461.png)

![Image](https://user-images.githubusercontent.com/91318807/217627859-82634a1b-e326-4cbd-848e-abbd47a3aaeb.png)

**Comment by Geczy** [comment]
i think i fixed this this morning
