### ISSUE TITLE
Show other icons (100+ rank) in MMR tracker

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#214]
Be tied not to mmr, but to rank
Depending on the rank, change the icon on the stream

![Image](https://user-images.githubusercontent.com/91318807/218277313-fe295610-8224-4097-ae2b-3f041b3fe628.png)

![Image](https://user-images.githubusercontent.com/91318807/220320674-89fad0e2-668f-4b75-9ce7-c87cac89154f.png)

![Image](https://user-images.githubusercontent.com/91318807/220319335-de2f9c86-79c4-4388-9d95-9bd41f00a87b.png)

**Comment by Geczy** [comment]
i believe its done now
