### ISSUE TITLE
!mute command or disable dotabod button

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#22]
something to disable globally

this should part from the channel as well

**Comment by Woody3797** [comment]
!part would be permanent i assume? While a global disable would temporarily disable bot functions till enabled again?

**Comment by Geczy** [comment]
neither are permanent, the only perm solution would be a "delete my account" button in dotabod dashboard

**Comment by Woody3797** [comment]
ah ok, so would !part stop dotabod from appearing in a twitch user's channel userlist?

**Comment by Geczy** [comment]
> ah ok, so would !part stop dotabod from appearing in a twitch user's channel userlist?

yeah part or the global disable button in dotabod dashboard
