### ISSUE TITLE
[twitch-chat] Reduce bot spam-ability 

### ISSUE THREAD

**Issue by Aluerie** [dotabod/backend#221]
Just reposting talks from discord -> I think the healthiest concept for the bot behavior model is when the bot can be fine-tuned to be the least disruptive, the least annoying. 

Precisely.

- [X] **The bot should ___not___ say anything unless retrospective feature is turned on.**
  Not a single phrase in chat should be untoggleable. 
  
  Currently, looks like there is no such phrases. But I will watch out.

- [x] **The bot should ___not___ respond to disabled commands.**
  because that's why they disabled the commands.
  
  Not exactly sure how to design this while keeping current option "Sorry, command is disabled" response, probably just a purple-switch in Commands page.
  
   We could put many setup-switch here in future like 
   * mention the command invoker (mention with reply feature or just @ them or not at all)
   * custom cd - eh idk why I'm spiraling, this is different ideas, issues, talks.
    
---
### Disclaimer 
* Geczy (maybe jokingly) asked me to PR this myself so feel free to assign this issue to me. 
* However while I'm eager to learn TS/JS/etc - I'm a total noob in those so it gonna take me a while :D I'm posting an issue for posterity and so I have some extra motivation since it clogs my issues tab 
* and so if one day you don't have anything else to fix - you can do it yourself 😢

**Comment by Aluerie** [comment]
![image](https://github.com/dotabod/backend/assets/33165440/adc03652-9748-4f85-bf8c-675c8919326c)

can't confirm :susge: looks like some respond, some don't while disabled (i have all of those disabled) idk if i need to start stream or something to fix it.

**Comment by Geczy** [comment]
they respond if your stream is not live? that sounds like a bug

**Comment by Geczy** [comment]
but i fixed the "this command has been disabled" message, which is what it ohught this issue was about

**Comment by Aluerie** [comment]
> they respond if your stream is not live?

Yes, the bot responds to some of disabled commands with "Stream not live PauseChamp" (stream is indeed offline) while expected behavior of this issue was: 

> The bot should not respond to disabled commands.

meaning "not respond at all". So I guess, it's a bug.

The list of commands that do that:
- [ ] ranked
- [ ] avg
- [ ] xpm
- [ ] gpm
- [ ] apm
- [ ] np
- [ ] smurfs
- [ ] gm
- [ ] lg
- [ ] hero
- [ ] builds
- [ ] delay
- [ ] rosh
- [ ] items

---

> but i fixed the "this command has been disabled" message

thanks 🎆
