### ISSUE TITLE
[Feature Suggestion] Hero names as 7tv emotes/import pack

### ISSUE THREAD

**Issue by Aluerie** [dotabod/backend#222]
I actually do not know if it is possible, but just an idea.

Feature for streamers to import ~130 7tv emotes matching hero names (600 emotes after all) 

For example. let's say I have a 7tv emote `(Marci)` and then `!np` response would like this:

![image](https://user-images.githubusercontent.com/33165440/219416570-9f7ac5ba-103d-4250-a1c4-b3b0ae189f6c.png)

While I can add all emotes manually, I guess, it would be interesting universal import idea.

Caveats: 
* we probably should want to use official hero-icons for this. Streamers will be able to rename their `marciAyaya` to be `(Marci)` if they want. 
* I don't think people type `(Heroname)` a lot but we should be careful with this so it doesn't cause THIS THAT THOSE disaster. 
* Spaces are a problem
* even more ridiculous suggestion would be to upload them as bot sub emotes or personal 7tv/bttv emotes but ofc, it's too ridiculous :D i dont think we can scrab ~130 emotes total from those anyway.

**Comment by Geczy** [comment]
https://dota2.fandom.com/wiki/Category:Hero_minimap_icons

i didn't have time to upload all hero icons to 7tv, **but if someone does this,** i can provide a "use hero emotes" button that removes spaces in hero names and assumes you have 7tv emotes all added for heroes

so ocne someone uploads all 130+ hero icons to 7tv, let me know and i will reopen this issue to work on it. the emotes in 7tv must be live for at least a week before i work on this ( to make sure 7tv doesn't remove them later )

**Comment by Aluerie** [comment]
But there is 7tv API, and images are on steam cdn. 

Well, okay, I will actually try to automate upload emotes this evening.

**Comment by dankYoff** [comment]
@Aluerie I basically downloaded all the images, I just need to add them to 7tv
[hero_icon.zip](https://github.com/dotabod/backend/files/10932505/hero_icon.zip)

**Comment by Aluerie** [comment]
you probably should add them under bracketed names, i.e. 
`(Marci)` bcs current !np command uses round-bracketed names. so it would be less work for techleed. 

eh fok, on my side of things, I can't figure out how to bot-upload emotes to 7tv, their docs are very vague x_x I don't even understand where to get 7tv token for authorization. 

well, thanks for starting it doing manually.
