### ISSUE TITLE
!lgs unknown

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#233]
dankYbat: !lgs
dotabod: Last game: win · 10/2/10 on Unknown · lasted 30 min. · [dotabuff.com/matches/7022014502](https://dotabuff.com/matches/7022014502)

It's better not to write, because it looks strange. You can only write the result (if you don't know which hero was the last match)

![Image](https://user-images.githubusercontent.com/91318807/219844151-45074e18-dbe1-46bd-be0c-15d588ccfbcb.png)

**Comment by Geczy** [comment]
fixed
