### ISSUE TITLE
!translated / !language

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#235]
Create a !translated command
- More people will know about the Discord
- More languages will appear: I think Japanese, French, and Spanish are among them.
- Translation errors will be corrected faster

This translation into English was done by techleed <3. You can translate into your native language by writing to our discord: discord.gg/9RHvxCCW

Questa traduzione in italiano è stata realizzata da Helle#3318 <3. Potete tradurre nella vostra lingua madre scrivendo al nostro discord: discord.gg/9RHvxCCW

**Comment by Geczy** [comment]
![Image](https://user-images.githubusercontent.com/1036968/222917536-905bd8b4-441f-494a-ae9c-d26de3026ba0.png)
