### ISSUE TITLE
!wr/!winrate 1-10

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#273]
Show the winrate with or against the player you played with in the same team:

!wl muerta

You have a winrate of 56% for 20 matches in one team and 90% for 40 matches in opposite teams

![Image](https://user-images.githubusercontent.com/91318807/223453392-dc7d8545-e7ab-4516-9bf8-867424efd7ed.png)

**Comment by Geczy** [comment]
not right now, maybe if we have more requesters (vote with thumbs up)

**Comment by Geczy** [comment]
eg `https://api.opendota.com/api/players/293731272/peers?included_account_id=196878136`
