### ISSUE TITLE
!lore command

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#33]
with !lore, use a Tldr bot for posting hero lore in chat so its not too long. and link to the lore on dota2.com

**Comment by dankYoff** [comment]
maybe send this in private messages

**Comment by dankYoff** [comment]
Discord bot [MangoByte](https://github.com/mdiller/MangoByte) can do this with this command
/lore                | Gets the lore of a hero, ability, or item

**Comment by Geczy** [comment]
yes, but is very long

i dont think my bot can send DMs because its not popular enough, only the big bots can do DMs like streamelements

**Comment by dankYoff** [comment]
then you can output a certain number of characters and also reset the continuation link
