### ISSUE TITLE
fix midas chatter

### ISSUE THREAD

**Issue by proximuspl** [dotabod/backend#338]
Hello,
If midas has 2 charges then the dotabod is going to chat "massivePIDAS Use midas" in infinite loop.

![Zrzut ekranu z 2023-08-14 o 15 23 12-fullpage](https://github.com/dotabod/backend/assets/107475705/2d9ba225-e9a5-48c7-940c-e0dba4998977)

Also, yesterday upgrade is not working as intended - the dotabod is still chatting that the midas was used to late after using the first charge.

**Comment by proximuspl** [comment]
![obraz](https://github.com/dotabod/backend/assets/107475705/315fece2-fc05-4969-93be-17d5881de78f)

Here are all cases:

```
15:38 dotabod: Spirit Breaker ma serię 5 zabójstw POGGIES
15:38 dotabod: massivePIDAS Użyj midasa
15:38 dotabod: Midas został w końcu użyty, 26 sekund za późno Madge
15:38 ProximusPL: 1 (courier with midas arived) -> 1 -> 0 (26 sec later)
15:39 dotabod: massivePIDAS Użyj midasa
15:40 ProximusPL: 0 -> 1
15:41 ProximusPL: 1 -> 2
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 ProximusPL: 2 -> 1
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 dotabod: massivePIDAS Użyj midasa
15:41 ProximusPL: 1 -> 0
15:41 dotabod: Midas został w końcu użyty, 34 sekund za późno Madge
```

if midas has 
* one charge:
  * then dotabod will send "use midas" only single time (correct [✅])
* two charges:
  * then dotabod will send "use midas" an infinite number of times (incorrect [❌])
  * 

if charges will change from 
* 1 to 0 then dotabod will send "midas used to late" (incorrect [❌])
* 2 to 1 then dotabod will not send any message (incorrect [❌])

**Comment by Geczy** [comment]
fixed the infinite loop, but keeping this issue open as the new midas messaging i think still isn't accurate on cd

**Comment by Geczy** [comment]
I think it’s fixed perfect
