### ISSUE TITLE
!item aliases sometimes not found/using search instead of alias

### ISSUE THREAD

**Issue by poecco** [dotabod/backend#353]
issue:
aliases (especially short ones) cause some buggy behaviour with search.

scenario: alch and lc in match, !items lc returns items for alch.
![alias_issue](https://github.com/dotabod/backend/assets/71287790/216eedcb-a399-4940-92f7-659438d484dd)

(not sure why this didn't work, there was a pa & pango ingame)
!items pa
![alias_issue2](https://github.com/dotabod/backend/assets/71287790/8a882a31-1925-433e-a57e-ef61ed614eee)

Don't think it's very rare, search probably causes too many possibilities.

ideas:
- start searching at characters > 3, only use aliases if 2 chars (might not fix all occurences)
or
- remove search and only use aliases/names, alot more control over userinput, probably works better overall. Downside is less flexible but imo this would probably be the way to go.

**Comment by Geczy** [comment]
I think I fixed it
