### ISSUE TITLE
turbo games are adjusting mmr

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#373]
fix so it only adjusts for ranked games

**Comment by Aluerie** [comment]
this is the only issue that pops up after searching for "turbo" so I will bring possibly related problems here;

Turbo games also
* get counted in !WL as ranked
* Aegis/Rosh chatter info is wrong. Correct is https://liquipedia.net/dota2/Game_Modes#Turbo_Mode
  * aegis lasts for 4 minutes 
  * rosh possible respawn timer is halved.

PS. This comment in the code  is wrong (min 4 max 5.5 because halving min 8 max 11)

https://github.com/dotabod/backend/blob/d19459a2f741c84b5fec6cf9b237a4a377d9b6f3/packages/dota/src/dota/events/gsi-events/event.roshan_killed.ts#L88

**Comment by Geczy** [comment]
Which one is actually turbo? My database only has lobby types 1, 7, 9, and 14. For some reason id 23 isn't being picked up...Might need to look into how to get lobby type again?

```js
const gameModes = [
  { id: 1, name: 'All Pick' },
  { id: 2, name: 'Captains Mode' },
  { id: 3, name: 'Random Draft' },
  { id: 4, name: 'Single Draft' },
  { id: 5, name: 'All Random' },
  { id: 6, name: 'Intro' },
  { id: 7, name: 'Diretide' },
  { id: 8, name: 'Reverse Captains Mode' },
  { id: 9, name: 'The Greeviling' },
  { id: 10, name: 'Tutorial' },
  { id: 11, name: 'Mid Only' },
  { id: 12, name: 'Least Played' },
  { id: 13, name: 'New Player Pool' },
  { id: 14, name: 'Compendium Matchmaking' },
  { id: 15, name: 'Custom Game' },
  { id: 16, name: 'Captains Draft' },
  { id: 18, name: 'Ability Draft' },
  { id: 19, name: 'Event Game' },
  { id: 20, name: 'All Random Deathmatch' },
  { id: 21, name: '1v1 Mid Only' },
  { id: 22, name: 'All Pick' },
  { id: 23, name: 'Turbo' },
  { id: 24, name: 'Mutation' },
]
```

**Comment by Aluerie** [comment]
Erm
> lobby types

> `const gameModes = [`

Lobby Type is a different thing from game mode. 

```py
class LobbyType(IntEnum):  # source: dota_gcmessages_common_lobby.proto
    Invalid          = -1
    Unranked         = 0
    Practice         = 1
    CoopBotMatch     = 4
    Ranked           = 7
    BattleCup        = 9
    LocalBotMatch    = 10
    Spectator        = 11
    EventGameMode    = 12
    NewPlayerMode    = 14
    FeaturedGameMode = 15
```

**Comment by Aluerie** [comment]
For example, GetRealTimeStats has them both
![image](https://github.com/user-attachments/assets/903284a5-155e-454f-b088-ed8795e422a6)

And so does TopSource GC Call
![image](https://github.com/user-attachments/assets/e3e361cc-0e5a-4cd2-b6b6-4e586a1858a7)

**Comment by Geczy** [comment]
have i been looking at the wrong key this whole time? lol

my code uses lobby_type === 7 a lot, so sounds like that's still fine, since there's different types of ranked game modes

but having turbos counted in !ranked sounds like a bug

does `!ranked` return incorrectly too during a turbo match? 

do you have a match id in the last 12 hours you can share, that was recorded on dotabod, which should be turbo but isn't counted as such?

**Comment by Aluerie** [comment]
haha, quick search in twitch tags "turbo" gave me this streamer https://www.twitch.tv/d0ters

their last game was 7955145008

!ranked worked properly (translation: no, it's not ranked)
![image](https://github.com/user-attachments/assets/6d2a9798-4356-4582-9f33-de106a6f257c)

**Comment by Geczy** [comment]
i see why it's happening now , i think because lobby type is 0. will check into it

**Comment by Aluerie** [comment]
rosh thing still wrong.

this is turbo game 7968975075, rosh fell at 33:04 so the response should be 37:04-38:34

![image](https://github.com/user-attachments/assets/fe80c0e4-65d6-4141-8797-e45349376d99)

**Comment by Geczy** [comment]
so is it wrong? lol

**Comment by Aluerie** [comment]
rosh timer is still wrong in turbo games. Here, rosh died at 16:26
 ![Image](https://github.com/user-attachments/assets/22391aa2-2f2d-4ebf-b446-16885f6ba38d)

mmr thing about turbo games is fixed, looks like?
