### ISSUE TITLE
Aegis timer shows on wrong hero

### ISSUE THREAD

**Issue by yckmm** [dotabod/backend#398]
Example from qojqva stream: https://www.twitch.tv/videos/2050863231?t=1h21m55s
Aegis picked up by Luna, but dotabod shows Ember picked up the aegis.

I assume it's a problem with Immortal Draft mode and the initial player draft slot being used instead of the actual team slot.

**Comment by Geczy** [comment]
oh sorry forgot to respond to this

yeah it's an annoying issue, i really thought i was able to fix it by now but appears not

does it still happen? i just released another update that hopefully helps

**Comment by yckmm** [comment]
just saw it happen again on qojqva's stream (or he didn't get the update yet?).

**Comment by Geczy** [comment]
fuck lol, weird issue for sure. trying to think of a good way to debug this in the future. might make a command to log it all if i ever see this happen and assign usage of the command out to several testers like yourself. whats your twitch user if you want to help report this? i'll build a command for this some time you can use to report the bug

**Comment by yckmm** [comment]
sure I can do that, 'Makenomistake' is my twitch name

**Comment by Geczy** [comment]
i think this issue is fixed now, can you let me know here if it's still happening? @yckmm
