### ISSUE TITLE
allow mods to login to dotabod dashboard for streamer

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#4]
dont show streamer overlay url to mods, as this should be private

reach out to twitch to get a list of mods for the streamer 

add mod log for actions taken for streamer

**Comment by Woody3797** [comment]
would it be better/easier to just allow mods to do certain things via twitch chat, like changing MMR/streamer IDs, add steamIDs to !np (when ready). While main functions like showing event messages, enabling predictions etc should be streamer side only

**Comment by Geczy** [comment]
@Woody3797 which actions specifically would you have allowable in twitch chat by mods? 

can already do `!mmr= <mmr> <steamid>` by mods
and i might make `<steamid>` replaced by `<name>` so like `!mmr= 5000 smurf`

**Comment by Woody3797** [comment]
changing event messages and adding IDs to !np in future.

for now i cant think of any, cus i feel anything related to overlay (aegis/mmr/medal) should be streamer side only, while anything related to twitch chat can be enabled/disabled by mods too (so maybe the predictions and event messages come to think of it, disregard my previous comment hahaha).

**Comment by Geczy** [comment]
this feature is complete

**Comment by Geczy** [comment]
https://dotabod.com/dashboard/moderators
