### ISSUE TITLE
!rosh

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#416]
From:
Roshan killed! Next roshan between 34:04 and 37:04 · Rosh deaths: 1 · Next drop: cheese. · Templar Assassin picked up the aegis!

To:
1 Roshan killed! · Templar Assassin picked up the aegis! · Next Roshan: 34:04-37:04 · Radiant/Dire: 31%/69% · Next drop: Cheese.

**Comment by Geczy** [comment]
What is 31/69?

**Comment by dankYoff** [comment]
@Geczy Chance of Roshan appearing on top or bottom
00:00, 05:00, ... .35:00, 40:00, and every five-minute time, he switches sides. 
If the time starts with 5, then Dire if 0 then Radiant.

There are three cases:
1) Roshan between 0 and 5. Radiant/Dire 100%/0%
2) Roshan between 5 and 0. Radiant/Dire 0%/100%
3) Roshan passes 0/5. Then the number of seconds through the key point depends, for example 34:04-37:04. 
Key point: 35:00.
1. 35:00-34:04=56c, 37:04-35:00=124s
2. 34:04-37:04=180s
3. 56s/180c=31%, 124s/180s=69%
Radiant/Dire: 31%/69%

I don’t think it’s necessary, just something new

**Comment by Geczy** [comment]
i thought roshan is top or bottom based on night or day?

**Comment by dankYoff** [comment]
Yes. However, you can calculate the probability of a roshan's appearance based on his death/availability in the roshpit.

I thought that the time for the appearance of the roshan was from 5 to 11 minutes, but in fact it is from 8-11 and there is no point in doing these calculations for the sake of these 3 minutes
![Image](https://github.com/user-attachments/assets/ade2f0f2-a347-41bb-b134-7175363a3047)

**Comment by dankYoff** [comment]
But after 8 minutes after killing a roshan, we can display an additional indicator of the % of rosha appearance, especially in lets or during teamfights, it is interesting to know how quickly it appears.
![Image](https://github.com/user-attachments/assets/52de16a7-7213-4bbd-a547-11e05782e47a)

**Comment by dankYoff** [comment]
useless!
