### ISSUE TITLE
disable mmr but enable medal tracking

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#5]
Then make 2 different commands and can toggle them as well

!medal !mmr

**Comment by Geczy** [comment]
done

**Comment by dankYoff** [comment]
![зображення](https://user-images.githubusercontent.com/91318807/215645830-1e90c772-e027-4269-9e8f-95043aaf2b08.png)

**Comment by Geczy** [comment]
have to use these toggles, then medal will only respond with medal 

maybe it doesnt make sense having !mmr respond with medal only, should maybe be medal only, but i wanted it to be global across all streams, same commands, similar responses 

![image](https://user-images.githubusercontent.com/1036968/215651906-2679bdd1-a22b-4edd-96c1-05277cdc8a13.png)

**Comment by dankYoff** [comment]
so the same problem
![зображення](https://user-images.githubusercontent.com/91318807/215741888-c45b344d-9a12-421e-bdb6-b4eab725f4aa.png)
