### ISSUE TITLE
add !gm heroname or !gm 1-10, same for !smurfs

### ISSUE THREAD

**Issue by XenSide** [dotabod/backend#65]
!medal heroname, herocolor, 1-10

**Comment by dankYoff** [comment]
maybe also for !lgs

**Comment by Geczy** [comment]
@dankYoff to get the last game score of a ally or enemy in current game?

**Comment by dankYoff** [comment]
yeap

**Comment by dankYoff** [comment]
only for !lgs, because !gm useless. maybe if you make separate commands !mmr and !medal(#157 ), then it will be possible to make the color, name and number for !medal
