### ISSUE TITLE
track which pick each hero was

### ISSUE THREAD

**Issue by XenSide** [dotabod/backend#71]
so we can do things like show 9th pick was zeus or last pick was sniper

or so we can hide overlay for each hero separately

i get a steam server id as soon as match is shown to draskyl to accept

i get the account ids as soon as game map is shown, or maybe during strategy phase once hero is picked for all team>?

maybe can Check clock time during picking for what to hide. Use css

**Comment by Geczy** [comment]
cant check clock time because hero picks are random places in the hero bar, so dont know which one to hide

there's no way to do this right now that i can think of for all regions
