### ISSUE TITLE
Bot hangs if someone abandons the game and it ends abruptly

### ISSUE THREAD

**Issue by XenSide** [dotabod/backend#72]
The bot either keeps tracking the old game or straight up stops responding

An example of a match where this happened is: 

MatchID: 6927814776
Quitter userID: 122042701  
Stremer userID: 109096474 VinsetVNS

Match dotabuff; https://www.dotabuff.com/matches/6927814776
UserID dotabuff; https://www.dotabuff.com/players/122042701

One example of this happening when the streamer is the one quitting the game can be found here: 

MatchID: 6928314868

Match Dotabuff: https://www.dotabuff.com/matches/6928314868

**Comment by Geczy** [comment]
https://github.com/dotabod/backend/commit/43789ef6ac021c07ee6f19a50e471fd78f5222da potential fix, need to confirm

**Comment by Geczy** [comment]
closing for now thinking it's fixed. re open if not fixed
