### ISSUE TITLE
One-Click Setup for ADHD people

### ISSUE THREAD

**Issue by XenSide** [dotabod/backend#74]
Add the option of running an installer to finish setup for people that can't be bothered or don't have the knowledge to.

Research needed on file storage of OBS sources

**Comment by dankYoff** [comment]
Is it possible to implement it, but as an idea, on the final slide, add a script that will automatically launch a dota with bots by pressing 1 button on the site
![зображення](https://user-images.githubusercontent.com/91318807/214307743-f118dae4-f83c-437c-b39a-e53c5ee2e4ae.png)

**Comment by dankYoff** [comment]
hm, cool feature, maybe for someone it is much easier to click a button on the site than to go to Steam and then click to open the dota. But so-so

**Comment by dankYoff** [comment]
STEPS
1 /mod dotabod 
2 Download config, save file to folder + `-gamestateintegration`. Restart (paste into console quit)
3 Obs. Create Stream Overlay scene
4 Start dota with bots

Is it really possible to do this by pressing 1 button in the browser? It is probably not very important now and you can postpone this idea for now and deal with the functionality of the bot first.

You need to create an ehe. a file (some stages can be implemented in the browser) in which there will be stages and the user will click the next button.

**Comment by Geczy** [comment]
yeah i would need to create an ahk script to do this for the user. but its not a big problem right now because a lot of users are doing it right after i added the videos

so for now i will close this, can maybe come back to it in the future if many people are still having trouble, or there is demand for one click setup

**Comment by Geczy** [comment]
this is impleneted

**Comment by Geczy** [comment]
obs setup too
