### ISSUE TITLE
[Suggestion] Please, make !commands chat-command to be toggleable as all other commands are

### ISSUE THREAD

**Issue by Aluerie** [dotabod/backend#77]
Basically title. Small reasoning is that some streamers prefer to set up `!commands` in their own way. Example would be mine (i dont want 100 bots to spam-answer it and there are complexities like custom prefixes or not fully customizable):
![image](https://user-images.githubusercontent.com/33165440/209400418-193f1cae-b366-40ec-8fd9-5269c842d39d.png)
where as you can see @dotabod slightly intervenes while I don't want it to be answering !commands. Pretty much all other bots have it customizable.

So, can this command get a toggle like all other commands? 
![image](https://user-images.githubusercontent.com/33165440/209400527-c8033df4-ce8d-412a-8e8b-fe2ec5a5245c.png)

Sorry if wrong repo.

**Comment by Geczy** [comment]
great idea, ill throw a toggle on it
