### ISSUE TITLE
add notable players under top hero bar

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#89]
https://discord.com/channels/1039887907705593876/1046119849014853775/1059952125360218162

(Idea) Overlay feature: notable players nickname under each hero icon. ( I know we can check it via commands but it may be useful for future VODs) 

to fix clutter: 
Middors: you could step them up and down. Like first name higher in line than second, then third in line with first, then 4th in line with 2nd

**Comment by dankYoff** [comment]
so good idea

**Comment by Geczy** [comment]
wrap the hero name 



![Image](https://user-images.githubusercontent.com/1036968/215354032-9dde87da-dfb8-4b2c-aeb3-e5d0906fe272.png)

**Comment by dankYoff** [comment]
your idea
@Geczy name appearing with a small interval with "toodoo"
