### ISSUE TITLE
!np function

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#9]
just like 9kmmrbot . add frontend to manage the list 

![image](https://user-images.githubusercontent.com/1036968/204886158-1fa88dda-006b-429a-92af-0e3affe4e927.png)

**Comment by Geczy** [comment]
ohh yeah, instead of adding a list of notable players manually?

**Comment by Woody3797** [comment]
yep, but still allow option for streamer/mod to add manually just like 9kmmrbot. if it isnt possible to parse steamIDs from the website, then just allowing mods to add would be enough

**Comment by Geczy** [comment]
added. its not possible to add custom players right now, its using a list of 2700 pro players
