### ISSUE TITLE
when playing with divine & immortal & ranked, bug in !avg

### ISSUE THREAD

**Issue by Geczy** [dotabod/backend#97]
![Image](https://user-images.githubusercontent.com/1036968/211893977-b8e8d935-3c1a-4261-931c-df7cc17550ca.png)

![Image](https://user-images.githubusercontent.com/1036968/211893899-d23c16de-aa36-4404-bfe4-d42a341b5b3f.png)

https://discord.com/channels/1039887907705593876/1046119849014853775/1061434667691155456

**Comment by dankYoff** [comment]
https://github.com/Hambergo/9kmmrbot/blob/typescript/src/commands/notablePlayers.ts

**Comment by Geczy** [comment]
> [Hambergo/9kmmrbot@`typescript`/src/commands/notablePlayers.ts](https://github.com/Hambergo/9kmmrbot/blob/typescript/src/commands/notablePlayers.ts?rgh-link-date=2023-01-12T14%3A04%3A52Z)

hambergo just gets mmr from steam api. i have to calculate manually because i don't use this api, as it's unreliable based on region (SEA and China) 

the bug is here https://github.com/dotabod/backend/blob/master/web/src/dota/lib/calculateAvg.ts

**Comment by dankYoff** [comment]
2 options:
the bot does not correctly receive data about the rank of players
the bot does not correctly calculate the average mmr of players

**Comment by dankYoff** [comment]
when i started streaming but without running match search it returned this result:
![зображення](https://user-images.githubusercontent.com/91318807/212448573-0b2d46b1-e3e3-451e-884e-e12035a2d877.png)

**Comment by dankYoff** [comment]
What do you think of parsi data from Excel or from variables: for each rating, write down your rating and round it depending on the level of opponents
Or derive a certain formula for the dependence of mmr on the rank, knowing several variables
![зображення](https://user-images.githubusercontent.com/91318807/213234698-3e46697d-f883-4e7c-a3b8-26ee548ae9b9.png)
[rang to mmr.xlsx](https://github.com/dotabod/backend/files/10448421/rang.to.mmr.xlsx)

**Comment by Geczy** [comment]
level of hero for the player? or level of what? 

the problem is i cannot know what mmr can be after immortal, like rank 10 vs rank 1000, do not know if its 7k mmr or 10k mmr

**Comment by dankYoff** [comment]
Well, if we can't get data about the mmr of the rank that comes after the immortal, there is a solution to the problem:

1) It is necessary to get data about the ranks of players, : 500, 600, 1000, 513, 361, immortal, 2000, immortal, 900, 400

2) Next, we refer to the data already recorded in the variables or in the excel table (500 - 8500, 600 - 8300, 7840, 8510, 8830, 5600, 7000, 5600, 7870, 8734)

3) We get the average rating formula.
aug=sum(8500, 8300, 7840, 8470, 8830, 5600, 7000, 5600, 7870, 8730))/10 = 7674 mmr | Immortal 1140

**Comment by dankYoff** [comment]
That is why I said that it is necessary to either derive a certain formula that will reduce the measurement or refer to certain data that are written in the table/variables that will return information about the mmr of a certain rank

**Comment by Geczy** [comment]
i like the formula you created. it will help. but isn't mmr different for ranks according to region? like NA and EU?

**Comment by dankYoff** [comment]
yeah thats a problem: for each region the rating is different
300 rank NA = 2000 rank EU
80 rank CN = 1000 rang EU

**Comment by Geczy** [comment]
so the next problem is, i dont know what region the user is queueing. i get some data that maybe i can figure it out, but its very hard. like i get steam server id, i dont know if this is useful

how is this formula?

```js
function calculateMMR(rank, region) {
  let mmr;

  if (rank === "Immortal") {
    mmr = 5630;
  } 

  let rankAdjustment = 1;
  if (region === "NA") {
    rankAdjustment = 2000 / 300;
  } else if (region === "CN") {
    rankAdjustment = 1000 / 80;
  }
  rank = rank * rankAdjustment;

  if (rank >= 1 && rank < 15) {
    mmr = 13000;
  } else if (rank >= 15 && rank < 70) {
    mmr = 11000;
  } else if (rank >= 70 && rank < 800) {
    mmr = 10000;
  } else if (rank >= 800 && rank < 2000) {
    mmr = 8000;
  } else if (rank >= 2000 && rank < 3500) {
    mmr = 7000;
  } else if (rank >= 3500 && rank < 5000) {
    mmr = 6500;
  } else if (rank >= 5000 && rank < 10000) {
    mmr = 6100;
  }
  return mmr;
}
```

**Comment by dankYoff** [comment]
```
if (rank >= 1 && rank < 5) {
    mmr = 13000;
if (rank >= 5 && rank < 15) {
    mmr = 12000;
  } else if (rank >= 15 && rank < 30) {
    mmr = 11000;
  } else if (rank >= 70 && rank < 100) {
    mmr = 10000;
  } else if (rank >= 200 && rank < 250) {
    mmr = 9000;
  } else if (rank >= 800 && rank < 2000) {
    mmr = 8000;
  } else if (rank >= 2000 && rank < 3500) {
    mmr = 7000;
  } else if (rank >= 3500 && rank < 5000) {
    mmr = 6500;
  } else if (rank >= 5000 && rank < 10000) {
    mmr = 6100;
  }
  return mmr;
}
```
There are 2 options:
1) get information about other ranks and make tests for this code
2) postpone this idea for the time being and look for other solutions to this problem

**Comment by dankYoff** [comment]
You can also change the order so that it starts from 5000 to 13000 instead of the other way around. Because probably most have 1000-2000 rank. Although I do not know how it will affect the speed of the code

**Comment by dankYoff** [comment]
There will be a very large error if we give a large number of ranks (rank >= 2000 && rank < 3500). There will be a very large fallibility (500-700 mmr)

**Comment by dankYoff** [comment]
I looked for projects on Github, maybe you can find an answer to this question
https://github.com/fobo66/WearMMR
https://github.com/heartofimpetus/DotaLass
https://github.com/Gansejunge/dota2-mmr-tracker

**Comment by Geczy** [comment]
https://github.com/Gansejunge/dota2-mmr-tracker/blob/master/local/screenshot.py this takes screenshots to find mmr 🤣 

https://github.com/heartofimpetus/DotaLass/blob/faa225cea9efe47325635840f907f8888780bc6a/DotaLass/API/PlayerDisplay.cs#L117 this uses mmr_estimate value from opendota, which is probably the best option we have, but opendota rate limits me :( i think i can come up with a way to do opendota api requests though that will prevent rate limiting

see example here of grubby, mmr estimate is inaccurate but pretty close https://api.opendota.com/api/players/849473199

can also look into opendota to see how they claculate estimate https://github.com/search?q=repo%3Aodota%2Fcore%20mmr_estimates&type=code

**Comment by Geczy** [comment]
https://github.com/odota/core/blob/7b37b3163ba8a1f084c94364be1eaa05f4b397c7/svc/counts.js#LL122C13-L122C20

i think odota gets estimate from the avg_mmr key that you can only get in steam client with protobuff match request. and this only works after a match is finished, or for a replay. so it will not work live

so requesting opendota api is the best way

but when the player profile is private, no estimate will be provided 

https://api.opendota.com/api/players/136393622

https://www.dotabuff.com/players/136393622

but dotabuff has an estimate, but no api

**Comment by Geczy** [comment]
im asking in opendota discord https://discord.com/channels/144629812982448128/246608091569848321/1066128508780290108

**Comment by Geczy** [comment]
https://api.opendota.com/api/players/321580662 yatoro, rank 5, is mmr estimate 5k? lol

https://www.opendota.com/players/321580662

i dont think opendota api for mmr estimate will help us either now

**Comment by Geczy** [comment]
so one solution we can do is claculate avg mmr using known values, 0-5600, and then calculate avg rank tier, and display both in !avg 

but is that useful? most chatters want to see mmr for the high rank players in avg, right? they dont care avg rank 

>dotabod: avg mmr: 5742, avg rank: 32

**Comment by dankYoff** [comment]
Yes, I think this is the best idea how it can be implemented. Many people are already used to 9kmmrbot, which is able to display the average rating of the match, and it seems to me that it is better for an ordinary viewer (a person who just joined the stream and does not know information about this match)

Therefore, it will be more correct for you to decide what to do in this situation, I can only say my point of view.

**Comment by dankYoff** [comment]
And if you say that you can get data about the average rating, then this will help you make the right formula for finding the average mmr.

It will also be possible to round the rank, that is, so that the result is constantly different

![зображення](https://user-images.githubusercontent.com/91318807/213866114-c5dfaeaf-78c8-4d25-b4e8-cd3bbdf1bdb0.png)

**Comment by dankYoff** [comment]
Also, I was thinking of creating a post in Discord or on Reddit, so that if there are people who want to, they could themselves provide data on mmr in different regions or change this data in the table

**Comment by dankYoff** [comment]
https://www.reddit.com/r/DotA2/comments/7fjegr/nightbot_rank_command_for_dota_2_streamers/

**Comment by Geczy** [comment]
that reddit only works on rank tiers that have an mmr, like divine and below

**Comment by Geczy** [comment]
> Stratz knows how to do it online during a match ![зображення](https://user-images.githubusercontent.com/91318807/214601501-a51a0548-df1b-4be2-aeb6-eb1fe45a3dcf.png)
> 

they just use the api that 9kmmrbot and valve uses i believe, its not their own calculation

**Comment by Geczy** [comment]
i think this strats page also does not work on all regions, can you confirm? like SEA and India / China

**Comment by dankYoff** [comment]
It counts for all regions. But it is not clear whether he correctly calculates avg.

You can do it in the following way, while calculating the average rating using api valve. So it is possible for certain regions, it will not count it correctly. But later, if there is an opportunity, then it will be possible to fix it when the decision comes.

Or not to display the average rating until now and wait for changes/a new idea to solve this problem

**Comment by dankYoff** [comment]
plattttt (twitch) can help with this table

> What do you think of parsi data from Excel or from variables: for each rating, write down your rating and round it depending on the level of opponents Or derive a certain formula for the dependence of mmr on the rank, knowing several variables ![зображення](https://user-images.githubusercontent.com/91318807/213234698-3e46697d-f883-4e7c-a3b8-26ee548ae9b9.png) [rang to mmr.xlsx](https://github.com/dotabod/backend/files/10448421/rang.to.mmr.xlsx)

**Comment by Aluerie** [comment]
Why there is a doubt that Game Coordinator API from Dota2client (not Steam rest api one as some comment above-above might be mixing) doesn't work for Sea? 


Im also user of it (my discord bot - AluBot) and it works fine for all regions except China bcs of their own perfect world servers that are soft-hidden. It basically shows all matches that Watch tab can show. And it indeed shows all games except China. 

---
But, I mean, do we have Chinese twitch streamers using dotabod? 

I'm not sure if it is practical to use some calculation workarounds when the only non-working region is the one that doesn't use on twitch.

**Comment by dankYoff** [comment]
It seems to me that you need to add mmr to !avg, !np, !gm. 

Yes, it counts it incorrectly, but that's not a problem, because people will know the approximate value

![Image](https://user-images.githubusercontent.com/91318807/219267863-4a2b93e1-77f7-4699-b75d-d35e0860dda6.png)

**Comment by Lypheo** [comment]
> > Stratz knows how to do it online during a match
> 
> they just use the api that 9kmmrbot and valve uses i believe, its not their own calculation

What API ist that? Is it documented anywhere?
