### ISSUE TITLE
rework chatter bounty

### ISSUE THREAD

**Issue by dankYoff** [dotabod/backend#99]
+120 gold from bounty EZ Clap Thanks Blue, Purple, Blue SeemsGood
to
+120 gold from bounty (3/4) EZ Clap Thanks Lifestealer x2, Dragon Knight SeemsGood
![зображення](https://user-images.githubusercontent.com/91318807/212218818-ed5f627f-76bb-45cb-b925-e88937478bd6.png)

**Comment by Geczy** [comment]
sadly can't add hero names because we may not have that data yet, its on a delay of 2m for spectator api 

but i can add the 3/4, and x2 , good idea
